# Generated by Django 4.2.10 on 2026-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="admin_passcode",
            field=models.CharField(
                default="admin1234",
                help_text="Passcode for the custom admin dashboard at /manage/",
                max_length=128,
            ),
        ),
    ]
