# Generated by Django 4.2.10 on 2026-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_learningmaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("excused", "Excused"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
