# Generated by Django 4.2.10 on 2026-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_attendancerecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="completed_weeks",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="core.curriculumweek"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="students_enrolled", to="core.course"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("software_development", "Software Development"),
                    ("ui_ux_design", "UI/UX Design"),
                    ("networking", "Networking"),
                    ("cybersecurity", "Cybersecurity"),
                    ("hardware_repair", "Hardware Repair"),
                    ("it_support", "IT Support"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
