# Generated by Django 4.2.10 on 2026-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_student_completed_weeks_student_courses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
