# Generated by Django 5.2.15 on 2026-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_student_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="password",
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
