# Generated by Django 5.2.15 on 2026-06-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_hash_existing_passwords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cohort",
            name="admin_passcode",
        ),
    ]
