# Generated by Django 5.2.15 on 2026-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_cohort_admin_passcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                choices=[
                    ("software_development", "Software Development"),
                    ("ui_ux_design", "UI/UX Design"),
                    ("networking", "Networking"),
                    ("cybersecurity", "Cybersecurity"),
                    ("it_support", "IT Support"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("software_development", "Software Development"),
                    ("ui_ux_design", "UI/UX Design"),
                    ("networking", "Networking"),
                    ("cybersecurity", "Cybersecurity"),
                    ("it_support", "IT Support"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
