# Generated by Django 4.2.10 on 2026-07-14 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="has_laptop",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="learningmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="learning_materials/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "ppt",
                            "pptx",
                            "xls",
                            "xlsx",
                            "zip",
                            "mp4",
                            "jpg",
                            "jpeg",
                            "png",
                            "txt",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="attachment_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachment_letters/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
