# Generated by Django 4.2.10 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_has_laptop_to_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submission_url",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submitted_at",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("not_submitted", "Not Submitted"), ("reviewed", "Reviewed")],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
