# Generated by Django 4.2.10 on 2026-07-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_submission_url_and_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_tokens",
                to="core.mentor",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_tokens",
                to="core.student",
            ),
        ),
    ]
