# Generated by Django 5.0.14 on 2026-09-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_mentor_to_password_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Lock attendance for this specific day.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mentor",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lock attendance for this entire week.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_locks",
                        to="core.curriculumweek",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
